matrix

diff --git a/.github/workflows/releases.yml b/.github/workflows/releases.yml
--- a/.github/workflows/releases.yml
+++ b/.github/workflows/releases.yml
@@ -13,6 +13,16 @@ jobs:
       - run: echo 'toto'
       - run: echo ${{ matrix.env }}
       - run: echo 'tata'
+      - run: |
+          echo ${{ inputs.github-ref }}
+          echo ${{ inputs.github-ref_name }}
+          echo ${{ inputs.github-ref_type }}
+          IFS='/' read -r REFS REF_TYPE REF_NAME <<< ${{ inputs.github-ref }}
+          IFS='.-' read -r MAJOR MINOR PATCH PRERELEASE_TYPE PRERELEASE_VERSION <<< $REF_NAME
+          echo $REFS
+          echo $REF_TYPE
+          echo $REF_NAME
+#          [[ $count -eq ${{ inputs.expected }} ]] || (echo "::error::Expected ${{ inputs.expected }} files, $count found." && exit 1)
 
 #      - uses: actions/checkout@v3
 #      - id: get-version
